CREATE TABLE "DATA_WAREHOUSE"."CUSTOMER"(
    CUSTOMERKEY VARCHAR(2000) PRIMARY KEY,
    CUSTOMERID VARCHAR(2000) NOT NULL,
    CUSTOMER VARCHAR(2000),
    CITY VARCHAR(2000),
    STATEPROVINCE VARCHAR(2000),
    COUNTRYREGION VARCHAR(2000),
    POSTALCODE VARCHAR(2000)
);


CREATE TABLE "DATA_WAREHOUSE"."PRODUCT"(
    PRODUCTKEY VARCHAR(2000) PRIMARY KEY,
    SKU VARCHAR(2000),
    PRODUCT VARCHAR(2000),
    STANDARDCOST NUMERIC,
    COLOR VARCHAR(2000),
    LISTPRICE NUMERIC,
    MODEL VARCHAR(2000),
    SUBCATEGORY VARCHAR(2000),
    CATEGORY VARCHAR(2000)
);

CREATE TABLE "DATA_WAREHOUSE"."SALES_ORDER"(
    SALESORDERLINEKEY VARCHAR(2000) PRIMARY KEY,
    CHANNEL VARCHAR(2000),
    SALESORDER VARCHAR(2000),
    SALESORDERLINE VARCHAR(2000)
);

CREATE TABLE "DATA_WAREHOUSE"."SALES_TERRITORY"(
    SALESTERRITORYKEY SERIAL PRIMARY KEY,
    REGION VARCHAR(2000),
    COUNTRY VARCHAR(2000),
    "GROUP" VARCHAR(2000)
);

CREATE TABLE "DATA_WAREHOUSE"."RESELLER"(
    RESELLERKEY VARCHAR(2000) PRIMARY KEY,
    RESELLERID VARCHAR(2000) NOT NULL,
    BUSINESSTYPE VARCHAR(2000),
    RESELLER VARCHAR(2000),
    CITY VARCHAR(2000),
    STATEPROVINCE VARCHAR(2000),
    COUNTRYREGION VARCHAR(2000),
    POSTALCODE VARCHAR(2000)
);


CREATE TABLE "DATA_WAREHOUSE"."SALES"(
    SALESORDERLINEKEY VARCHAR(2000),
    RESELLERKEY VARCHAR(2000) ,
    CUSTOMERKEY VARCHAR(2000),
    PRODUCTKEY VARCHAR(2000),
    ORDERDATEKEY DATE ,
    DUEDATEKEY DATE NOT NULL,
    SHIPDATEKEY VARCHAR(2000),
    SALESTERRITORYKEY VARCHAR(2000) NOT NULL,
    ORDERQUANTITY NUMERIC NOT NULL,
    UNITPRICE NUMERIC NOT NULL,
    EXTENDEDAMOUNT NUMERIC,
    UNITPRICEDISCOUNTPCT NUMERIC,
    PRODUCTSTANDARTCOST NUMERIC,
    TOTALPRODUCTCOST NUMERIC,
    SALESAMOUNT NUMERIC,
    PRIMARY KEY (SALESORDERLINEKEY, RESELLERKEY, CUSTOMERKEY, 
                 PRODUCTKEY, ORDERDATEKEY, SALESTERRITORYKEY)
);
CREATE TABLE "DATA_WAREHOUSE"."DIM_TIEMPO" (
    FechaID VARCHAR(200) PRIMARY KEY,
    FechaSK VARCHAR(200),
    Fecha DATE,
    Año INTEGER NOT NULL,
    Trimestre INTEGER NOT NULL,
    Mes INTEGER NOT NULL,
    Semana INTEGER NOT NULL,
    Dia INTEGER NOT NULL,
    DiaSemana INTEGER NOT NULL,
    NTrimestre VARCHAR(7) NOT NULL,
    NMes VARCHAR(15) NOT NULL,
    NMes3L VARCHAR(3) NOT NULL,
    NSemana VARCHAR(10) NOT NULL,
    NDia VARCHAR(6) NOT NULL,
    NDiaSemana VARCHAR(10) NOT NULL
);


DO $$
DECLARE
    IdIni INTEGER := 1;
    FechaDesde DATE := DATE '2000-01-01';
    FechaHasta DATE := MAKE_DATE(EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER + 5, 12, 31);
BEGIN
    WHILE FechaDesde <= FechaHasta LOOP
        INSERT INTO CLASEBI.DIM_TIEMPO (
            FechaID,
            FechaSK,
            Fecha,
            Año,
            Trimestre,
            Mes,
            Semana,
            Dia,
            DiaSemana,
            NTrimestre,
            NMes,
            NMes3L,
            NSemana,
            NDia,
            NDiaSemana
        )
        VALUES (
            IdIni,
            EXTRACT(YEAR FROM FechaDesde)::TEXT || LPAD(EXTRACT(MONTH FROM FechaDesde)::TEXT, 2, '0') || LPAD(EXTRACT(DAY FROM FechaDesde)::TEXT, 2, '0'),
            FechaDesde,
            EXTRACT(YEAR FROM FechaDesde),
            EXTRACT(QUARTER FROM FechaDesde),
            EXTRACT(MONTH FROM FechaDesde),
            EXTRACT(WEEK FROM FechaDesde),
            EXTRACT(DAY FROM FechaDesde),
            EXTRACT(DOW FROM FechaDesde) + 1,
            'T' || EXTRACT(QUARTER FROM FechaDesde)::TEXT || '/' || RIGHT(EXTRACT(YEAR FROM FechaDesde)::TEXT, 2),
            TO_CHAR(FechaDesde, 'FMMONTH'),
            TO_CHAR(FechaDesde, 'FMMon'),
            'Sem ' || EXTRACT(WEEK FROM FechaDesde)::TEXT || '/' || RIGHT(EXTRACT(YEAR FROM FechaDesde)::TEXT, 2),
            TO_CHAR(FechaDesde, 'DD MON'),
            TO_CHAR(FechaDesde, 'FMDay')
        );

        IdIni := IdIni + 1;
        FechaDesde := FechaDesde + INTERVAL '1 day';
    END LOOP;
END $$;
